// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");

// Minimal Prisma config placeholder to avoid TypeScript build errors
// Some environments may not have `prisma/config` available during build.
// Export as CommonJS to match project's package.json type.
module.exports = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
